#!/bin/sh

set -e

case "$1" in
    configure)
        CONF='/etc/rogcore.conf'
        if [ -f $CONF ]; then
            mv $CONF $CONF.save 
        fi
        systemctl unmask rog-core.service
        #ROG=$(lsusb |grep 0b05 |cut -d ' ' -f 6 |cut -d ':' -f 2)
        #sed -i -e "s|==/"1866/"|==/"${ROG}/"|g" /etc/udev/rules.d/99-rog-core.rules
        ;;

    *)
        ;;
esac

#DEBHELPER#

exit 0
